<a href="https://colab.research.google.com/github/sevval-345/NLP/blob/main/Basit_Metin_%C4%B0%C5%9Fleme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
import nltk
from bs4 import BeautifulSoup
from urllib.request import urlopen
raw = urlopen("https://www.turkcellesirket.com/destek-merkezi").read()

raw1 = BeautifulSoup(raw)
raw2 = raw1.get_text()
#print(raw2)

from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer("^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}).([a-zA-Z]{2,5})")
tokenizer.tokenize(raw2)

<>:12: SyntaxWarning: invalid escape sequence '\-'
<>:12: SyntaxWarning: invalid escape sequence '\-'
/tmp/ipykernel_9264/992209973.py:12: SyntaxWarning: invalid escape sequence '\-'
  tokenizer = RegexpTokenizer("^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}).([a-zA-Z]{2,5})")


[('destek', 'eplatform', 'com', 'tr')]

**Vector Kavramı ve Count Vectorizer**

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
# corpus, külliyat, derlem
ans = "Turkcell ile bağlan hayata"
ans2 = "Turkcell ile dünyalar senin olsun"
ans3 = "Turkcell ile Turkcell calisiyor"
ans4 = "Turkcell Turkcell hareketler"
matrix = CountVectorizer(max_features=1000)
X = matrix.fit_transform([ans,ans2,ans3,ans4]).toarray()
print(X)
X2 = matrix.transform(["Turkcell cok seviyorum"]).toarray()
print(X2)

print(matrix.get_feature_names_out())

[[1 0 0 0 1 1 0 0 1]
 [0 0 1 0 0 1 1 1 1]
 [0 1 0 0 0 1 0 0 2]
 [0 0 0 1 0 0 0 0 2]]
[[0 0 0 0 0 0 0 0 1]]
['bağlan' 'calisiyor' 'dünyalar' 'hareketler' 'hayata' 'ile' 'olsun'
 'senin' 'turkcell']


In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Örnek veri kümesi (pozitif ve negatif cümleler)
# Corpus / külliyat / derlem
texts = [
    "I love this product",       # pozitif
    "This is an amazing movie",  # pozitif
    "I am very happy with the service",  # pozitif
    "I hate this thing",         # negatif
    "This is the worst experience ever", # negatif
    "I am not happy with this",  # negatif
    "I feel wonderful", #positif
    "I love the product", #positif
    "Great this product is awesome", #positif
    "Great I hate this product"  #negatif
]
labels = [1, 1, 1, 0, 0, 0, 1, 1, 1,0]  # 1 = pozitif, 0 = negatif


# Metinleri vektöre çevir
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)
# Veri setini eğitim/test olarak ayır
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.3, random_state=42)

# Lojistik regresyon modeli
model = LogisticRegression()
model.fit(X_train, y_train)

# Tahmin yap ve sonucu değerlendir
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

# Yeni metinleri tahmin et
new_texts = ["I love the experience", "I feel terrible", "What a wonderful day", "This is not good"]
new_X = vectorizer.transform(new_texts)
predictions = model.predict(new_X)

# Sonuçları göster
for text, label in zip(new_texts, predictions):
    sentiment = "Pozitif" if label == 1 else "Negatif"
    print(f"'{text}' -> {sentiment}")


              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       2.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0

'I love the experience' -> Pozitif
'I feel terrible' -> Pozitif
'What a wonderful day' -> Pozitif
'This is not good' -> Negatif


In [8]:
X.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
        0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0]])

In [9]:
print(vectorizer.get_feature_names_out())


['am' 'amazing' 'an' 'awesome' 'ever' 'experience' 'feel' 'great' 'happy'
 'hate' 'is' 'love' 'movie' 'not' 'product' 'service' 'the' 'thing' 'this'
 'very' 'with' 'wonderful' 'worst']


In [11]:

from textblob import TextBlob

# İngilizce örnekler
texts = [
    "I love this product",
    "This is terrible",
    "What a great day!",
    "I hate this",
    "It's okay, not bad",
    "Great it does not work",
    "I feel terrible"
]

print("Sentiment Analizi (TextBlob):")
for text in texts:
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity
    label = "Pozitif" if polarity > 0 else "Negatif" if polarity < 0 else "Nötr"
    print(f"'{text}' -> {label} ({polarity:.2f})")


Sentiment Analizi (TextBlob):
'I love this product' -> Pozitif (0.50)
'This is terrible' -> Negatif (-1.00)
'What a great day!' -> Pozitif (1.00)
'I hate this' -> Negatif (-0.80)
'It's okay, not bad' -> Pozitif (0.42)
'Great it does not work' -> Pozitif (0.80)
'I feel terrible' -> Negatif (-1.00)


In [12]:
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
import torch

# 1. Hızlı prototipleme için pipeline kullanımı
classifier = pipeline("sentiment-analysis", model="dbmdz/bert-base-turkish-cased")

# 2. Örnek cümle
text = "satın aldığım ürün çok başarılı ve çok memnunum"
#"Great it does not work" #chain of thought, reasoning
# "I hate to hurt someone"
# hurt someone (action) -> sentiment

# 3. Tahmin yap
result = classifier(text)
print("Sentiment Prediction:", result)

# 4. Alternatif olarak model ve tokenizer'ı doğrudan yükle (gelişmiş kullanım)
tokenizer = AutoTokenizer.from_pretrained("dbmdz/bert-base-turkish-cased")
model = AutoModelForSequenceClassification.from_pretrained("dbmdz/bert-base-turkish-cased")

# 5. Tokenleştirme ve Tensor'a dönüştürme
inputs = tokenizer(text, return_tensors="pt")

# 6. Modelin tahmin çıktısını alma
with torch.no_grad():
    logits = model(**inputs).logits
    probabilities = torch.nn.functional.softmax(logits, dim=1)

# 7. Sonuçları yazdırma
labels = ["NEGATIVE", "POSITIVE"]
predicted_label = labels[probabilities.argmax()]
print(f"Detailed Prediction: {predicted_label} ({probabilities.max().item()*100:.2f}%)")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/445M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: dbmdz/bert-base-turkish-cased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.seq_relationship.weight                | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/251k [00:00<?, ?B/s]

Sentiment Prediction: [{'label': 'LABEL_0', 'score': 0.5082119107246399}]


Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: dbmdz/bert-base-turkish-cased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.seq_relationship.weight                | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


Detailed Prediction: POSITIVE (71.31%)
